[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
marketplace = "FXUQwDsKJNrYFsfiUokPbH4BSrZtoC9m8HpoiMvYxtSE"

[registry]
url = "https://api.apr.dev"

#[provider]
#cluster = "localnet"
#wallet = "~/.config/solana/id.json"

[provider]
cluster = "Devnet"
wallet = "./HTurbin3-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test.validator]
url = "https://api.devnet.solana.com"
#url = "https://turbine-solanad-4cde.devnet.rpcpool.com/168dd64f-ce5e-4e19-a836-f6482ad6b396";


[[test.validator.clone]]
address = "J748azokS8cKaiGKgN5hsTsTuB1FJ1ikVNXKjq9DQnjg"

[[test.validator.clone]]
address = "43qXTGQdvEiPYj9GQvDfvQi7Shx8ahSd3d2sYBeEizuR" #mock data feed driver leaves

[[test.validator.clone]]
address = "9jfL52Gmudwee1RK8yuNguoZET7DMDqKSR6DePBJNXot" #mock data feed driver leaves


